name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  auto-release:
    name: Auto Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Increment Version
        id: increment_version
        run: |
          # Write a script to increment the version
          # This is just a placeholder, you should replace it with your logic
          # Example:
          # current_tag=$(git describe --tags --abbrev=0)
          # new_tag=$(echo $current_tag | awk -F. '{print $1 "." $2 "." $3+1}')
          # echo "::set-output name=new_tag::$new_tag"
          echo "::set-output name=new_tag::v1.0.0" # Placeholder, replace with actual logic
      
      - name: Create New Tag
        run: |
          new_tag=$(echo "${{ steps.increment_version.outputs.new_tag }}")
          git tag $new_tag
          git push origin $new_tag
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.new_tag }}
          release_name: ${{ steps.increment_version.outputs.new_tag }}
          draft: false
          prerelease: false
