# Your workflow file
name: Semantic Release

on:
  push:
    branches:
      - main
      - dev/*
      - feature/*
      - hotfix/*

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release published flag
        id: set_release_published
        run: echo "::set-output name=release_published::${{ steps.semantic.outputs.new_release_published }}"

      - name: Do something when a new release published
        if: steps.set_release_published.outputs.release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Commit Changelog
        run: |
          if [[ "${{ steps.set_release_published.outputs.release_published }}" == 'true' ]]; then
            git add CHANGELOG.md
            git commit -m "chore(release): update changelog"
          fi
